# Generated by Django 4.2.5 on 2023-11-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_delete_color'),
        ('cart', '0004_alter_cart_customer_alter_cart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.size'),
        ),
    ]
