# Generated by Django 4.2.5 on 2023-12-18 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wish',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
