# Generated by Django 4.2.5 on 2023-11-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={'blank': 'Поле не может быть пустым'}, max_length=128),
        ),
    ]
