# Generated by Django 4.2.5 on 2023-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_delete_color'),
        ('product', '0002_remove_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(related_name='brands', to='category.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='category.size'),
        ),
    ]
