# Generated by Django 4.2.5 on 2023-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_delete_color'),
        ('product', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='product_sizes', to='category.size'),
        ),
    ]
