# Generated by Django 4.2.5 on 2023-11-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_color'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
