# Generated by Django 4.2.5 on 2023-10-16 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('sent', 'Отправлен'), ('awaits', 'Ожидает получения'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='created', max_length=16),
        ),
    ]
