# Generated by Django 4.2.5 on 2023-09-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создан'), (2, 'Собран'), (3, 'Отправлен'), (4, 'Доставлен'), (5, 'Получен'), (6, 'Завершен'), (7, 'Отменен'), (8, 'Удален')], default=1),
        ),
    ]
