# Generated by Django 4.2.5 on 2023-10-16 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1003, unique=True, validators=[django.core.validators.MinValueValidator(1001)]),
        ),
    ]
