# Generated by Django 4.2.5 on 2023-09-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_address_is_main_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
