# Generated by Django 4.2.5 on 2023-10-16 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1001)]),
        ),
    ]
