# Generated by Django 4.2.5 on 2023-10-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создан'), (2, 'В обработке'), (3, 'Отправлен'), (4, 'Ожидает получения'), (5, 'Завершен'), (6, 'Отменен')], default=1, max_length=1),
        ),
    ]
