# Generated by Django 4.2.5 on 2023-11-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryType',
            new_name='Delivery',
        ),
    ]
