# Generated by Django 4.2.5 on 2023-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_deliverytype_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
