# Generated by Django 4.2.5 on 2023-11-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='delivery',
        ),
    ]
