# Generated by Django 4.2.5 on 2023-11-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_rename_price_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='price',
        ),
    ]
