# Generated by Django 4.2.5 on 2023-11-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_rename_total_price_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
