# Generated by Django 4.2.5 on 2023-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
