# Generated by Django 4.2.5 on 2023-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, default=1001, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
