# Generated by Django 4.2.5 on 2023-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='is_pickup',
        ),
        migrations.AddField(
            model_name='delivery',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
