# Generated by Django 4.2.5 on 2023-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_delivery_is_pickup_delivery_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
