# Generated by Django 4.2.5 on 2023-11-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
