# Generated by Django 4.2.5 on 2023-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='info',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(),
        ),
    ]
