# Generated by Django 4.2.5 on 2023-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'В обработке'), (2, 'Отправлен'), (3, 'Ожидает получения'), (4, 'Завершен')], default=0),
        ),
    ]
