# Generated by Django 4.2.5 on 2023-11-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_lastuseraddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastUserAddress',
            new_name='Address',
        ),
    ]
