# Generated by Django 4.2.5 on 2023-12-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
